"""Add workspace_id

Revision ID: 4f26e0891f0b
Revises: 0001_initial
Create Date: 2026-08-08 01:30:16.275715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f26e0891f0b'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_history', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_homework_history_workspace_id'), 'homework_history', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'homework_history', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_history', type_='foreignkey')
    op.drop_index(op.f('ix_homework_history_workspace_id'), table_name='homework_history')
    op.drop_column('homework_history', 'workspace_id')
    # ### end Alembic commands ###
